(setq mew-name "Ryoto Tomita")
(setq mew-ssl-verify-level 2)
(setq mew-ssl-cert-directory "/etc/pki/tls/certs/ca-bundle.crt")
(setq mew-prog-ssl-arg "CAfile=/etc/pki/tls/certs/ca-bundle.crt\n")
(setq mew-use-cached-passwd t)
(setq mew-passwd-timer-unit 60)
(setq mew-imap-size 0)
(setq mew-config-alist
'(("default"
("user" . "USER_NAME")
("mail-domain" . "DOMAIN_PART")
("smtp-server" . "smtp.mail.yahoo.co.jp")
("proto" . "%")
("imap-server" . "imap.mail.yahoo.co.jp")
("mailbox-type" . imap)
("inbox-folder" . "%inbox")
("fcc" . "%Sent")
("imap-trash-folder" . "%Trash")
("imap-ssl" . t)
("imap-auth" . pass)
("imap-user" . "MAIL_ADDR")
("smtp-ssl" . t)
("smtp-auth-list" . ("LOGIN"))
("smtp-user" . "MAIL_ADDR"))))
